project_id = "btspzagknvsbzyhwfvkh"

[functions.weather]
verify_jwt = true

[functions.crop-recommendation]
verify_jwt = true

[functions.pest-diagnosis]
verify_jwt = false

[functions.chat]
verify_jwt = true